In [1]:
import numpy as np


In [2]:
x=np.array([1,2,4,5])

In [3]:
print(x)

[1 2 4 5]


In [4]:
print(type(x))

<class 'numpy.ndarray'>


In [1]:
y=[2,3,4,5]
print(y)

[2, 3, 4, 5]


In [4]:
import numpy as np
l=[]
for i in range(1,5):
 int_1=int(input("enter"))
 l.append(int_1)
print(np.array(l))

enter 2
enter 3
enter 4
enter 5


[2 3 4 5]


In [19]:
import numpy as np

arr2 = np.array ([[1, 2, 3, 4], [5, 6, 7, 8]])  # A 2D list
#arr2_np = np.array(arr2)  # Convert to NumPy array

print("NumPy Array:")
print(arr2)

print("Number of dimensions:")
print(arr2.ndim)  # ndim shows the number of dimensions of the array


NumPy Array:
[[1 2 3 4]
 [5 6 7 8]]
Number of dimensions:
2


In [20]:
arr3=np.array([[[1,2,3,4],[1,2,3,4],[1,3,5,6]]])
print(arr3)
print(np.array(arr3.ndim))

[[[1 2 3 4]
  [1 2 3 4]
  [1 3 5 6]]]
3


In [6]:
import numpy as np
arr=np.array([1,2,3,4],ndim=10)
print(arr)

TypeError: array() got an unexpected keyword argument 'ndim'

In [8]:
#array filled 0's and 1's
import numpy as np
arr_zeros=np.zeros((3,4))
print(arr_zeros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [16]:
ones_1=np.ones((3,4))
ar_np=np.arange(4)
print(ones_1)
print()
print(ar_np)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

[0 1 2 3]


In [17]:
arr_dia=np.eye(9)
print(arr_dia)


[[1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [19]:
arr_lin=np.linspace(0,10,num=5)
print(arr_lin)


[ 0.   2.5  5.   7.5 10. ]


In [4]:
#create Numpy array with random number
import numpy as np
var=np.random.rand(4)
print(var)
var2=np.random.rand(2,5)
print(var2)


[0.88048588 0.59116868 0.39816342 0.92177705]
[[0.64658373 0.33606596 0.71594715 0.51843454 0.49295603]
 [0.96523073 0.86209131 0.4728859  0.35554416 0.08537155]]


In [5]:
var3=np.random.randn(2,3)
print (var3)
#for printing random no clode to zero and also generates a negative number

[[-0.54849587  1.68936377  1.9496031 ]
 [ 0.24672339  0.13897962 -0.31457684]]


In [6]:
var4=np.random.ranf(3)
print(var4)

[0.23862804 0.36331615 0.00861167]


In [7]:
#for a given range from [min,max,range]
var5=np.random.randint(5,30,7)
print(var5)

[13 12 22 21 25  7  5]


Data type

In [9]:
import numpy as np
var=np.array([1,2,3,4])
print("Data Type :",var.dtype)

Data Type : int64


In [11]:
var=np.array([1.0,2.0,5.7])
print("data types is :",var.dtype)

data types is : float64


In [12]:
var=np.array(["a","b",'c'])
print("data types is :",var.dtype)

data types is : <U1


In [13]:
var=np.array(['a','b',1.0,2.0,5.7])
print("data types is :",var.dtype)

data types is : <U32


In [15]:
 var=np.array([1,2,5],dtype="f")
print("data types is :",var.dtype)
print(var)

data types is : float32
[1. 2. 5.]


In [17]:
x2=np.array([1,2,3,4])
new=np.float32(x2)
new_ones=np.int_(new)
print("data types is :",new.dtype)
print("data types is :",x2.dtype)
print(x2)
print(new)

data types is : float32
data types is : int64
[1 2 3 4]
[1. 2. 3. 4.]


ARITHMETIC OPERATIONS IN NUMPY ARRAY

In [19]:
import numpy as np
vr=np.array([1,2,3,4])
vr_1=vr+5
print(vr_1)

 

[6 7 8 9]


In [20]:
vr1=np.array([1,2,3,4])
vr2=np.array([1,2,3,4])
varadd=vr1+vr2
print(varadd)

[2 4 6 8]


In [21]:
var=np.array([1,2,3,4])
car=var%3
print(car)

[1 2 0 1]


In [23]:
#2d array
vr1=np.array([[1,2,3,4],[1,3,6,9]])
vr2=np.array([[1,2,3,4],[1,3,6,9]])
varadd=vr1+vr2
print(varadd)

[[ 2  4  6  8]
 [ 2  6 12 18]]


In [25]:
var=np.array([1,2,3,4,5,6,78,9])
print("min:",np.min(var))
print("max:",np.max(var))

min: 1
max: 78


In [27]:
var=np.array([1,2,3,4,5,6,7,8])
print("min:",np.min(var),np.argmin(var))
print("sqrt",np.sqrt(var))
#argmin and argmax is the function that returns the min and max index of the element in the array

min: 1 0
sqrt [1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712]


In [28]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
cumulative_sum = np.cumsum(arr)
print("Original array:", arr)
print("Cumulative sum:", cumulative_sum)


Original array: [1 2 3 4 5]
Cumulative sum: [ 1  3  6 10 15]


Explanation:
this is cumsum 
Step 1: 1
Step 2: 1 + 2 = 3
Step 3: 1 + 2 + 3 = 6
Step 4: 1 + 2 + 3 + 4 = 10
Step 5: 1 + 2 + 3 + 4 + 5 = 15

SHAPE

In [30]:
#Shape the Array
import numpy as np
var=np.array([[1,2],[3,4]])
print(var)
print()
print(var.shape)


[[1 2]
 [3 4]]

(2, 2)


In [32]:
#Reshape the array
var2=np.array([1,2,3,4,5,6,7,8,9])
x=var2.reshape(3,3)
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
 #Broadcasting in the Numpy arrays
import numpy as np
var1=np.array([1,2,3,4])
print(var1[-3])
print(var1[1])

2
2


In [12]:
#indexing and slicing and iterating in the Numpy array
var2 =np.array([[[3,4],[1,2],[6,7]]])
print(var2)
print()
print(var2[0,2,1])


[[[3 4]
  [1 2]
  [6 7]]]

7


In [20]:
#SLICING THE ARRAY
import numpy as np

var = np.array([1, 2, 3, 4, 5, 6])
print(var)
print()
print("2 to 5", var[1:5])

var = np.array([[9, 8, 7, 6, 5, 4, 3, 2, 1], [1, 2, 3, 4, 5, 6]])
print(var)  # Print the 2D array to see its structure
print()
print(var[:4])  # This will NOT do what you expect in a 2D array
print("8 to 5:", var[0, 1:6]) #Corrected slicing for the 2D array
print("3 to end:", var[1, 2:]) #Corrected slicing for the 2D array

[1 2 3 4 5 6]

2 to 5 [2 3 4 5]


ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [21]:
var = np.array([3,4,5,6])
print(var)
print()
for i in var:
    print(i)

[3 4 5 6]

3
4
5
6


In [22]:
var3=np.array([[[9,8,7,6],[4,5,3,2]]])
print(var3)
print(var3.ndim)
print()
for i in var3:
    print(i)

[[[9 8 7 6]
  [4 5 3 2]]]
3

[[9 8 7 6]
 [4 5 3 2]]


In [25]:
var1 = np.array([[1,2,3,4],[1,2,3,4]])
print(var1)

for j in var1:
    print(j)
print()

for k in var1:
    for l in k:
     print(l)

[[1 2 3 4]
 [1 2 3 4]]
[1 2 3 4]
[1 2 3 4]

1
2
3
4
1
2
3
4


In [28]:
var3=np.array([[[1,2,3,4,5],[1.2,2.3,3.4,4.5,5.6]]])
print(var3)
print()
print(var3.ndim)

for i in var3:
    for j in i:
        for k in j:
            print(k)

[[[1.  2.  3.  4.  5. ]
  [1.2 2.3 3.4 4.5 5.6]]]

3
1.0
2.0
3.0
4.0
5.0
1.2
2.3
3.4
4.5
5.6


In [31]:
#iteration ke lie instead of for loop we can use nditer()
var3=np.array([[[9,8,7,6],[1,2,3,4]]])
print(var3)
print()
print(var3.ndim)
print()

for i in np.nditer(var3):
 print(i)

[[[9 8 7 6]
  [1 2 3 4]]]

3

9
8
7
6
1
2
3
4


In [34]:
var3=np.array([[[9,8,7,6],[1,2,3,4]]])
print(var3)
print()
print(var3.ndim)
print()

for i,d in np.ndenumerate(var3):
 print(i,d)

[[[9 8 7 6]
  [1 2 3 4]]]

3

(0, 0, 0) 9
(0, 0, 1) 8
(0, 0, 2) 7
(0, 0, 3) 6
(0, 1, 0) 1
(0, 1, 1) 2
(0, 1, 2) 3
(0, 1, 3) 4


In [2]:
#COPY AND VIEW IN NUMPY
import numpy as np
var=np.array([1,2,3,4])
co=var.copy()

print("var :",var)
print("copy :",co)
var[1]=88
print("copy:",co)


var : [1 2 3 4]
copy : [1 2 3 4]
copy: [1 2 3 4]


In [4]:
import numpy as np
var=np.array([1,2,3,4])
co=var.view()

print("var :",var)
print("view :",co)
var[1]=88
print("view:",co)


var : [1 2 3 4]
view : [1 2 3 4]
view: [ 1 88  3  4]


In [2]:
import numpy as np

var = np.array([1,2,3,4])
var1=np.array([9,8,7,6])

ar = np.concatenate((var,var1))

print(ar)

[1 2 3 4 9 8 7 6]


In [3]:
vr=np.array([[1,2],[3,4]])
vr1=np.array([[5,6],[7,8]])
 
ar = np.concatenate((vr,vr1))

print(ar)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [7]:
import numpy as np

var=np.array([1,2,3,4,5,6,7])

print(var)

ar=np.array_split(var,3)
print(ar)

[1 2 3 4 5 6 7]
[array([1, 2]), array([3, 4]), array([5]), array([6]), array([7])]


In [2]:
import numpy as np
var = np.array([1,2,3,2,4,5,2,5,2,8,9])
x=np.where(var ==2 )
print(x)


(array([1, 3, 6, 8]),)


In [4]:
var_3=np.array(['a','s','d','f'])
f=[True,False,True,False]
new_1=var_3[f]
print(new_1)
print(type(new_1))

['a' 'd']
<class 'numpy.ndarray'>


In [5]:
import numpy as np
var=np.array([1,2,3,4,5,6])
np.random.shuffle(var)
print(var)

[3 5 1 4 2 6]


In [11]:
var1 = np.array([1,2,3,3,4,5,2,3,4,5,6,7,8])
y=np.resize(var1,(2,4))
print(y)
x=np.unique(var1)
print(x)
print(y)

[[1 2 3 3]
 [4 5 2 3]]
[1 2 3 4 5 6 7 8]
[[1 2 3 3]
 [4 5 2 3]]


In [12]:
var1=np.array([1,2,3,4])
d=np.delete(var1,2)
print(d)

[1 2 4]


#MATRIX

In [ ]:
import numpy as np

# Define a square matrix
matrix = np.array([[1, 2], [3, 4]])

# Compute determinant
determinant = np.linalg.det(matrix)

print("Determinant:", determinant)


In [3]:
import numpy as np
var = np.array([[1,2,3],[1,2,3]])
print(var)
print(type(var))

[[1 2 3]
 [1 2 3]]
<class 'numpy.ndarray'>


In [4]:
var=np.matrix([[1,2,3],[4,5,6]])
print(np.transpose(var))

[[1 4]
 [2 5]
 [3 6]]


In [ ]:
#the end goodbye
'''1. Array Creation
np.array() - Create an array.
np.zeros() - Create an array filled with zeros.
np.ones() - Create an array filled with ones.
np.empty() - Create an empty array.
np.arange() - Create an array with evenly spaced values.
np.linspace() - Create an array with linearly spaced values.
np.eye() - Create an identity matrix.
np.random.rand() - Random values in a given shape.
np.random.randint() - Random integers in a given range.

    
2. Array Manipulation
np.reshape() - Reshape an array.
np.ravel() - Flatten an array.
np.transpose() - Transpose an array.
np.concatenate() - Join arrays along an axis.
np.stack() - Stack arrays along a new axis.

    
3. Mathematical Operations
np.add() - Element-wise addition.
np.subtract() - Element-wise subtraction.
np.multiply() - Element-wise multiplication.
np.divide() - Element-wise division.
np.dot() - Dot product of two arrays.
np.sqrt() - Element-wise square root.
np.power() - Element-wise power.
np.exp() - Exponential of all elements.
np.sin(), np.cos(), np.tan() - Trigonometric functions.

    
4. Statistical Functions
np.mean() - Compute the mean.
np.median() - Compute the median.
np.std() - Compute the standard deviation.
np.var() - Compute the variance.
np.min() - Minimum value.
np.max() - Maximum value.

    
5. Linear Algebra Functions
np.linalg.det() - Determinant of a matrix.
np.linalg.inv() - Inverse of a matrix.
np.linalg.eig() - Eigenvalues and eigenvectors.
np.linalg.norm() - Norm of a matrix or vector.
np.linalg.solve() - Solve linear matrix equations.

    
6. Logical Functions
np.all() - Test if all elements are true.
np.any() - Test if any element is true.
np.where() - Return elements based on condition.
np.logical_and(), np.logical_or(), np.logical_not() - Logical operations.


7. Sorting and Searching
np.sort() - Sort an array.
np.argsort() - Returns the indices that would sort an array.
np.argmax() - Index of the maximum value.
np.argmin() - Index of the minimum value.

    
8. Array Comparison
np.equal() - Check element-wise equality.
np.not_equal() - Check element-wise inequality.
np.greater() - Check if elements are greater.
np.less() - Check if elements are less.


9. Random Functions
np.random.seed() - Set the random seed.
np.random.normal() - Generate normal distribution.
np.random.choice() - Randomly pick elements from an array.'''
